# Generated by Django 4.2.9 on 2024-02-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_appointment_token_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('doctornotes', models.TextField()),
                ('medicine', models.TextField()),
                ('test', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.patient')),
            ],
        ),
    ]
