# Generated by Django 4.2.9 on 2024-02-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='dosage',
            field=models.CharField(default='', max_length=150),
        ),
    ]
