# Generated by Django 4.2.9 on 2024-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
