# Generated by Django 4.2.9 on 2024-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_medicine_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
