# Generated by Django 4.2.9 on 2024-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
