# Generated by Django 4.2.9 on 2024-02-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='high_range',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='low_range',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
