# Generated by Django 4.2.9 on 2024-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_alter_test_high_range_alter_test_low_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='high_range',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='low_range',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
